
FROM node:14.17.0

# Set the working directory in the container that is present in frontend that also have some code files that want to be known to our docker file or  image that we are creating 

WORKDIR /usr/src/app

 # this cmd is for Copy package.json and package-lock.json to the working directory for ignor the cunfusion
COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
